### ISSUE TITLE
XML not showing on window when being opened after incorrect XML

### ISSUE THREAD

**Issue by jmdarling** [UTD-SESeniorDesign-Spring2015-Group4/Simulation-Configuration-Tool#1]

**Comment by cam1911** [comment]
Difficulty recreating the error. Opening a configuration will have lag, showing a blank GUI, but after approximately 15secs of inactivity, or resizing the window, the XML shows.

**Comment by jmdarling** [comment]
You need to force the interface to redraw after opening the configuration then

**Comment by jmdarling** [comment]
`setVisible(true)` may work
